from enum import StrEnum


class RequestState(StrEnum):
    SUBMITTED = "SUBMITTED"
    PROFILE_RESOLVED = "PROFILE_RESOLVED"
    OTP_PENDING = "OTP_PENDING"
    OTP_LOCKED = "OTP_LOCKED"
    RECOVERY_PENDING = "RECOVERY_PENDING"
    VERIFIED = "VERIFIED"
    PREAPPROVED = "PREAPPROVED"
    AUTO_APPROVED = "AUTO_APPROVED"
    DIPLOMAT_REVIEW = "DIPLOMAT_REVIEW"
    GOVERNMENT_REVIEW = "GOVERNMENT_REVIEW"
    APPROVED = "APPROVED"
    DECLINED = "DECLINED"
    CLOSED = "CLOSED"
